version: "3.8"

services:
  # DynamoDB Local para desenvolvimento
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: finassist-dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      # IMPORTANTE: Usar diretório do WSL2, NÃO do Windows (/mnt/c)
      # Isso evita erros de permissão sqlite no WSL2
      - ~/dynamodb_data:/data
    networks:
      - finassist-network
    restart: unless-stopped

networks:
  finassist-network:
    driver: bridge
